spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/java-training
    userName: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    clean-disabled: false
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration

server:
  port: 8080
